### ISSUE TITLE
Review button disabled with the optional field

### ISSUE THREAD

**Issue by obajide028** [techstudioconsults/Productize#117]
![WhatsApp Image 2024-08-21 at 11 57 29](https://github.com/user-attachments/assets/26f295c3-fd7b-4bb9-ba32-4bc31682f0e6)

**Comment by techstudioconsults** [comment]
this is not a bug, you have to write a review, its a mandatory requirement.

**Comment by obajide028** [comment]
> this is not a bug, you have to write a review, its a mandatory requirement.
> 
> 

Alright 👍
