### ISSUE TITLE
Users can't view product for digital product after purchase

### ISSUE THREAD

**Issue by obajide028** [techstudioconsults/Productize#123]

**Comment by techstudioconsults** [comment]
The downloaded products (digital or skill selling) should have a unique key type `product_type: digital_product` 
endpoint `/products/purchased`, `/skillSellings/products/:id` and `/digitalProduct/products/:id`

![image](https://github.com/user-attachments/assets/ec848f6d-9711-4159-8128-0d57700f67e2)

**Comment by techstudioconsults** [comment]
also add the necessary info of the user on all endpoint specified above .
